# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dionysus
email: sjwjames325@gmail.com
description: This is an awesome game maker website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://sjwjames.xyz" # the base hostname & protocol for your site
github_username:  sjwjames

# Build settings
markdown: kramdown
